### ISSUE TITLE
双击后没反应

### ISSUE THREAD

**Issue by xiangxiang464** [lsy223622/XDUClassVideoDownloader#6]
打包好的 exe 程序，双击后啥也没有怎么解决呀
![image](https://github.com/user-attachments/assets/bb86ae04-db6d-4d7b-b21a-0559d1bd7f15)

**Comment by lsy223622** [comment]
可以看一下这个文件的属性里面有没有解除下载文件保护，或者会不会是进程被杀毒软件挂起了。
之前没见过这样子的现象，如果能有更多相关信息也许能找到问题所在。

**Comment by xiangxiang464** [comment]
重启电脑又可以了，哈哈
之前都是可以下的，只是今天早上的时候半天没反应
