### ISSUE TITLE
课程名称中出现`:`导致下载失败

### ISSUE THREAD

**Issue by dlct-wzx** [lsy223622/XDUClassVideoDownloader#7]
课程名称中出现`:`会导致下载失败，在配置文件中删除课程名称中的`:`后可正常下载
![IMG_8380](https://github.com/user-attachments/assets/2c9ab48f-d8b5-4877-b875-4c6889eb0c8b)

**Comment by dlct-wzx** [comment]
win下文件名称中不能包含< > / \ | :  * ?

**Comment by lsy223622** [comment]
看来是我忘了这个问题，感谢大佬的 pr
